#!/usr/bin/env bash

set -ex

make CC=${CC}

dd if=/dev/zero of=disk.img count=$((1024*16)) bs=1024
mkfs/mkfs.mfs -B 4096 disk.img
mkdir disk
src/fuse-mfs -o allow_other,default_permissions,use_ino,attr_timeout=0 disk.img disk

pushd disk
make -C ../test/pjd-fstest
sudo prove -r ../test/pjd-fstest/tests
popd

fusermount -u disk
fsck/fsck.mfs disk.img
